### ISSUE TITLE
Нарушается контракт hashCode и equals

### ISSUE THREAD

**Issue by AlphaBeth** [Bowl-of-noodles/Lab3#3]
https://github.com/Bowl-of-noodles/Lab3/blob/8d865581d89662a7f43ff9169200c96c59318609/src/edu/Rogachova/entities/Piglet.java#L80-L91

**Comment by AlphaBeth** [comment]
https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--

> If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result.

**Comment by Bowl-of-noodles** [comment]
https://github.com/Bowl-of-noodles/Lab3/blob/97e89a8b15cc5d21229dfd22bd71464ac766b9b4/src/edu/rogachova/entities/Piglet.java#L96

**Comment by AlphaBeth** [comment]
Контракт всё ещё нарушен.

**Comment by AlphaBeth** [comment]
Здесь тоже нарушен
https://github.com/Bowl-of-noodles/Lab3/blob/97e89a8b15cc5d21229dfd22bd71464ac766b9b4/src/edu/rogachova/description/Home.java#L70-L84

**Comment by AlphaBeth** [comment]
Все ещё нарушается, плюс нарушения появляются в новых местах

https://github.com/Bowl-of-noodles/Lab3/blob/9637f8898a127acb819f451705f36c86d5ece287/src/edu/rogachova/water/Groove.java#L56-L71

https://github.com/Bowl-of-noodles/Lab3/blob/9637f8898a127acb819f451705f36c86d5ece287/src/edu/rogachova/water/River.java#L41-L56

https://github.com/Bowl-of-noodles/Lab3/blob/9637f8898a127acb819f451705f36c86d5ece287/src/edu/rogachova/water/Stream.java#L40-L56
